//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.FastTrack.SMATWorkbookGenerator.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.FastTrack.SMATWorkbookGenerator.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports the output from the SMAT tool into the specifed workbook template..
        /// </summary>
        internal static string AppDisplayDesc {
            get {
                return ResourceManager.GetString("AppDisplayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft FastTrack SMAT Workbook Generator.
        /// </summary>
        internal static string AppDisplayTitle {
            get {
                return ResourceManager.GetString("AppDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file specified ({0}) could not be found, please ensure the path is correct..
        /// </summary>
        internal static string ConfigurationFileDoesNotExist {
            get {
                return ResourceManager.GetString("ConfigurationFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value:.
        /// </summary>
        internal static string HelpDefaultValueText {
            get {
                return ResourceManager.GetString("HelpDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\\?|-help|-\?.
        /// </summary>
        internal static string HelpFlagRegEx {
            get {
                return ResourceManager.GetString("HelpFlagRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string HelpOptionalText {
            get {
                return ResourceManager.GetString("HelpOptionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMAT workbook generation complete. The generated workbook can be found at {0}..
        /// </summary>
        internal static string ImportCompleteMsgFormat {
            get {
                return ResourceManager.GetString("ImportCompleteMsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit..
        /// </summary>
        internal static string PressAnyKeyToExit {
            get {
                return ResourceManager.GetString("PressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the required property &quot;{0}&quot;.
        /// </summary>
        internal static string RequiredPropNotFoundExceptionMsg {
            get {
                return ResourceManager.GetString("RequiredPropNotFoundExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source directory specified ({0}) does not exist..
        /// </summary>
        internal static string SourceFolderDoesNotExist {
            get {
                return ResourceManager.GetString("SourceFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary file does not exist in the source folder..
        /// </summary>
        internal static string SummaryFileDoesNotExist {
            get {
                return ResourceManager.GetString("SummaryFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template file specified ({0}) could not be found, please ensure the path is correct..
        /// </summary>
        internal static string TemplateFileDoesNotExist {
            get {
                return ResourceManager.GetString("TemplateFileDoesNotExist", resourceCulture);
            }
        }
    }
}
